class Ex8_4 {
	public static void main(String args[]) {
		System.out.println(1);// 출력			
		System.out.println(2);// 출력
		try {
			System.out.println(3);// 출력
			System.out.println(0/0);// 예외 발생
			System.out.println(4); 	// 예외가 발생한 이후 문장은 실행되지 않는다.
		} catch (ArithmeticException ae)	{//일치 되는 catch문 실행
			if (ae instanceof ArithmeticException) 
				System.out.println("true");	// true 출력
			System.out.println("ArithmeticException");// 출력
		} catch (Exception e){
			System.out.println("Exception");// 출력 x
			// Exception 모든 예외의 최고 조상 마지막 catch블럭 설정
		}	// try-catch의 끝
		System.out.println(6);
	}	// main메서드의 끝
}
